enum Permission {
  USERPRODUCT_CAN_VIEW = 'USERPRODUCT_CAN_VIEW',
  USERPRODUCT_CAN_CREATE = 'USERPRODUCT_CAN_CREATE',
  USERPRODUCT_CAN_EDIT = 'USERPRODUCT_CAN_EDIT',
  USERPRODUCT_CAN_DELETE = 'USERPRODUCT_CAN_DELETE'
}
export default Permission;
