enum Permission {
  PARTNER_CAN_VIEW = 'PARTNER_CAN_VIEW',
  PARTNER_CAN_CREATE = 'PARTNER_CAN_CREATE',
  PARTNER_CAN_EDIT = 'PARTNER_CAN_EDIT',
  PARTNER_CAN_DELETE = 'PARTNER_CAN_DELETE'
}
export default Permission;
