enum Permission {
  PARTNERUSER_CAN_VIEW = 'PARTNERUSER_CAN_VIEW',
  PARTNERUSER_CAN_CREATE = 'PARTNERUSER_CAN_CREATE',
  PARTNERUSER_CAN_EDIT = 'PARTNERUSER_CAN_EDIT',
  PARTNERUSER_CAN_DELETE = 'PARTNERUSER_CAN_DELETE'
}
export default Permission;
