enum Permission {
  GENERATELINK_CAN_VIEW = 'GENERATELINK_CAN_VIEW',
  GENERATELINK_CAN_CREATE = 'GENERATELINK_CAN_CREATE',
  GENERATELINK_CAN_EDIT = 'GENERATELINK_CAN_EDIT',
  GENERATELINK_CAN_DELETE = 'GENERATELINK_CAN_DELETE'
}
export default Permission;
