enum Permission {
  USERHEIRS_CAN_VIEW = 'USERHEIRS_CAN_VIEW',
  USERHEIRS_CAN_CREATE = 'USERHEIRS_CAN_CREATE',
  USERHEIRS_CAN_EDIT = 'USERHEIRS_CAN_EDIT',
  USERHEIRS_CAN_DELETE = 'USERHEIRS_CAN_DELETE'
}
export default Permission;
